version: '3.2'
services:
  clj-dev:
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile-dev
    image: safkalista_clj_dev_image:latest
    container_name: safkalista_clj_dev_container
    stdin_open: true
    tty: true
    volumes:
      - .:/safkalista
    ports:
      - 5555:5555
      - 3001:3001
      - 3000:3000
      - 4443:443
  db:
    build:
      context: .
      dockerfile: scripts/docker/Dockerfile-dev-db
    image: safkalista_db_dev_image:latest
    container_name: safkalista_db_dev_container
    environment:
      POSTGRES_PASSWORD: 'testi'
    expose:
      - 5430
    ports:
      - 5430:5432
  pgbackups3:
    image: schickling/postgres-backup-s3
    links:
      - db
    environment:
      SCHEDULE: '@every 1m'
      S3_REGION: eu-west-1
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_SAFKA}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET}
      S3_BUCKET: safkalistabackup
      S3_PREFIX: backup
      POSTGRES_DATABASE: safkalista
      POSTGRES_USER: safkalista_user
      POSTGRES_PASSWORD: possu
      POSTGRES_HOST: safkalista_db_dev_container
      POSTGRES_PORT: 5432
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
