FROM clojure:temurin-21-lein
COPY target/uberjar/server.jar /usr/src/safkalista/
ADD resources /usr/src/safkalista/resources
WORKDIR /usr/src/safkalista/
EXPOSE 3001
CMD ["java", "-jar", "server.jar"]
