version: '3.2'
services:
  clj-dev:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: safkalista_clj_dev_image:latest
    container_name: safkalista_clj_dev_container
    stdin_open: true
    tty: true
    volumes:
      - .:/safkalista
    ports:
      - 5555:5555
      - 3000:3000
      - 4443:443
  db:
    build:
      context: .
      dockerfile: Dockerfile-dev-db
    image: safkalista_db_dev_image:latest
    container_name: safkalista_db_dev_container
    environment:
      POSTGRES_PASSWORD: 'testi'
    ports:
      - 5434:5432
